# Generated by Django 5.2.8 on 2026-01-28 00:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_alter_productvariant_is_visible'),
        ('sellers', '0003_alter_seller_avatar_alter_seller_background_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(help_text='User related to this Cart', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Product variant quantity', validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('price_snapshot', models.DecimalField(decimal_places=2, help_text='Product variant price snapshot', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='price snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('cart', models.ForeignKey(help_text='Cart related to this CartItem', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='cart')),
                ('product_variant', models.ForeignKey(help_text='Product Variant related to this CartItem', on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='product variant')),
                ('seller', models.ForeignKey(help_text='Seller related to this CartItem', on_delete=django.db.models.deletion.CASCADE, to='sellers.seller', verbose_name='seller')),
            ],
            options={
                'verbose_name': 'CartItem',
                'verbose_name_plural': 'CartItems',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='product_variants',
            field=models.ManyToManyField(help_text='Product variants related to this Cart', through='cart.CartItem', to='products.productvariant', verbose_name='product variants'),
        ),
    ]
