# Generated by Django 5.2.8 on 2026-01-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0010_alter_productvariant_is_visible'),
        ('sellers', '0003_alter_seller_avatar_alter_seller_background_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product_variant'), name='unique_cart_item'),
        ),
    ]
