services:
  backend:
    container_name: mp-backend-dev
    build:
      context: ..
      dockerfile: Dockerfile
    image: mp-backend-dev
    pull_policy: build
    ports:
      - "${DJANGO_PORT}:8000"
    volumes:
      - ..:/app/
    env_file:
      - ../.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy
