# Generated by Django 5.2.8 on 2026-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, help_text='Avatar', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
