# Generated by Django 5.2.8 on 2026-01-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(help_text='Avatar', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
