# Generated by Django 5.2.8 on 2026-03-13 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Phone number', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='The phone number must be in the format: +999999999, and the maximum length is 20', regex='^\\+\\d{9,20}$')], verbose_name='phone number'),
        ),
    ]
