# Generated by Django 5.2.8 on 2026-03-13 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='updated at')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('google', 'Google')], max_length=32, verbose_name='provider name')),
                ('provider_uid', models.CharField(db_index=True, verbose_name='provider uid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Social account',
                'verbose_name_plural': 'Social accounts',
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider'), models.UniqueConstraint(fields=('provider_uid', 'provider'), name='unique_provider_uid')],
            },
        ),
    ]
