# Generated by Django 5.2.8 on 2026-03-20 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider_uid',
            field=models.CharField(verbose_name='provider uid'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['provider_uid', 'provider'], name='authenticat_provide_6f6b19_idx'),
        ),
    ]
