# Generated by Django 5.2.8 on 2026-04-05 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_socialaccount_provider_uid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='updated at')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('google', 'Google')], max_length=32, verbose_name='provider name')),
                ('provider_uid', models.CharField(verbose_name='provider uid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_providers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Auth provider',
                'verbose_name_plural': 'Auth providers',
            },
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
        migrations.AddIndex(
            model_name='authprovider',
            index=models.Index(fields=['provider_uid', 'provider'], name='authenticat_provide_7c1dc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='authprovider',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='authprovider',
            constraint=models.UniqueConstraint(fields=('provider_uid', 'provider'), name='unique_provider_uid'),
        ),
    ]
