# Generated by Django 5.2.8 on 2025-12-01 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid7, editable=False, help_text='Product uuid', primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(help_text='Product slug', unique=True, verbose_name='slug')),
                ('title', models.CharField(db_index=True, help_text='Product title', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Product description', null=True, verbose_name='description')),
                ('short_description', models.CharField(blank=True, help_text='Short product description', max_length=500, null=True, verbose_name='short description')),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Is product visible', verbose_name='is visible')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid7, editable=False, help_text='Product variant uuid', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Product variant title', max_length=200, verbose_name='title')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, help_text='Product variant price', max_digits=10, verbose_name='price')),
                ('stock', models.PositiveIntegerField(db_index=True, default=0, help_text='Product variant in stock', verbose_name='stock')),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Is product variant visible', verbose_name='is visible')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product variant',
                'verbose_name_plural': 'Product variants',
            },
        ),
    ]
