# Generated by Django 5.2.8 on 2025-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Product slug', max_length=300, unique=True, verbose_name='slug'),
        ),
    ]
