# Generated by Django 5.2.8 on 2025-12-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='uuid',
            new_name='id',
        ),
    ]
