# Generated by Django 5.2.8 on 2025-12-08 16:47

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_create_trgm_extension'),
        ('products', '0003_rename_uuid_product_id_rename_uuid_productvariant_id'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Is product visible', verbose_name='is visible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Product title', max_length=255, verbose_name='title'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_at'], name='products_pr_updated_150263_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'
                ),
                name='product_title_trgm_gin_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper('description'), name='gin_trgm_ops'
                ),
                name='product_desc_trgm_gin_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper('short_description'), name='gin_trgm_ops'
                ),
                name='product_short_desc_trgm_idx',
            ),
        ),
    ]
