# Generated by Django 5.2.8 on 2025-12-09 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_is_visible_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Product variant price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
