# Generated by Django 5.2.8 on 2026-01-03 17:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productvariant_price'),
        ('sellers', '0002_alter_seller_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Reviews average rating', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='reviews average rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, help_text='Reviews count', verbose_name='reviews count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller', verbose_name='seller'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Product variant price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='price'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='updated at')),
                ('rating', models.SmallIntegerField(default=1, help_text='Review rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('text', models.TextField(help_text='Review text', verbose_name='text')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Product review',
                'verbose_name_plural': 'Product reviews',
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_product_review')],
            },
        ),
    ]
