# Generated by Django 5.2.8 on 2026-01-06 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_reviews_avg_rating_product_reviews_count_and_more'),
        ('sellers', '0002_alter_seller_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['reviews_count'], name='products_pr_reviews_fd77f8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['reviews_avg_rating'], name='products_pr_reviews_d689a3_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product_id', 'created_at'], name='products_pr_product_2f6626_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product_id', 'rating'], name='products_pr_product_739017_idx'),
        ),
    ]
