# Generated by Django 5.2.8 on 2026-01-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_products_pr_reviews_fd77f8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Product description', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Short product description', max_length=500, verbose_name='short description'),
            preserve_default=False,
        ),
    ]
