# Generated by Django 5.2.8 on 2026-01-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(condition=models.Q(('is_visible', True), ('stock__gt', 0)), fields=['product_id'], name='idx_variant_product_search'),
        ),
    ]
