# Generated by Django 5.2.8 on 2026-01-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_idx_variant_product_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Is product variant visible', verbose_name='is visible'),
        ),
    ]
