# Generated by Django 5.2.8 on 2026-03-21 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productvariant_is_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product_id', 'user_id'], name='products_pr_product_eab03a_idx'),
        ),
    ]
