# Generated by Django 5.2.8 on 2025-11-27 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='updated at')),
                ('name', models.CharField(help_text='Seller name', max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Seller description', null=True, verbose_name='description')),
                ('avatar', models.CharField(blank=True, help_text='Seller avatar', max_length=255, null=True, verbose_name='avatar')),
                ('background', models.CharField(blank=True, help_text='Seller background image', max_length=255, null=True, verbose_name='background')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
