# Generated by Django 5.2.8 on 2026-01-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='avatar',
            field=models.CharField(help_text='Seller avatar', max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='background',
            field=models.CharField(help_text='Seller background image', max_length=255, null=True, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Seller description', verbose_name='description'),
            preserve_default=False,
        ),
    ]
